version: 2

jobs:
  lint:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint

  flow:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Flow
            command: yarn run flow
  test:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

  build:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build

  deploy-master:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Deploy
            command: ./deploy-master.sh
  deploy-pr:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Deploy
            command: ./deploy-pr.sh

workflows:
  version: 2

  deploy:
    jobs:
      - deploy-master:
          filters:
            branches:
              only:
                - master
      - deploy-pr:
          filters:
            branches:
              ignore:
                - master

  test:
    jobs:
      - lint
      - flow
      - build