version: 2

jobs:
  lint:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint

  flow:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Flow
            command: yarn run flow
  test:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

  build:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build

  deploy:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build
        - run:
            name: Deploy
            command: now

  alias:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build
        - run:
            name: Deploy
            command: now alias


workflows:
  version: 2

  deploy:
    jobs:
      - deploy
      - alias:
          filters:
            branches:
              only:
                - master

  test:
    jobs:
      - lint
      - flow
      - build