version: 2

jobs:
  lint:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Lint
            command: yarn run lint

  flow:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Flow
            command: yarn run flow
  test:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Run Tests & Check Coverage
            command: yarn run test:coverage

  build:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Build package
            command: yarn run build

  deploy-master:
      working_directory: ~/henribeck.im
      docker:
        - image: circleci/node:8@sha256:9338349847d15234034a0db79c2db604c403e4e41f7b762e7d7a48162a20f91e
      steps:
        - checkout
        - run:
            name: Install Packages
            command: yarn install
        - run:
            name: Deploy
            command: ./deploy-master.sh

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - build
      - deploy-master:
          requires:
            - lint
            - flow
            - build
          filters:
            branches:
              only:
                - master